library(qpdf)


file <- filebu
file2 <- "~/Dropbox/Clients/Ergon/Ergon business units.Font.Red_line/"
  
pdf_combine(c(
  
  paste0(file2,"misc/", "Intro.pdf"),
  paste0(file2,"misc/", "Table of contents.pdf"),
  paste0(file2,"misc/", "Methodology.pdf"),
  paste0(file2,"misc/", "Images_id_perf.pdf"),
  paste0(file2,"misc/", "Demographic data_title.pdf"),
  paste0(file,"sample overview plots/", "LOCATION - COUNT.pdf"),
  paste0(file,"sample overview plots/", "TENURE - COUNT.pdf"),
  paste0(file,"sample overview plots/", "ROLE - COUNT.pdf"),
  paste0(file,"sample overview plots/", "GENERATION - COUNT.pdf"),
  paste0(file2,"misc/", "CPI_title.pdf"),
  paste0(file2,"misc/", "CPI_descr.pdf"),
  paste0(file2,"misc/", "Company_CPI_scores.pdf"),
  paste0(file2,"misc/", "Company_CPI_vs_Global_scores.pdf"),
  paste0(file,"by all dimensions plots/", "All - Quadrant - Direction.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Vision.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Strategy.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Leadership.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file,"by all dimensions plots/", "All - Quadrant - Operations.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Adaptability.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Performance.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Systems.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file,"by all dimensions plots/", "All - Quadrant - People.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Development.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Talent.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Teamwork.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file,"by all dimensions plots/", "All - Quadrant - Engagement.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Fit.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Customer.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Climate.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "qtc.pdf"),
  paste0(file2,"misc/", "Employee_engagement_title.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Positivity.pdf"),
  paste0(file,"by all dimensions plots/", "All - Dimension - Satisfaction + Effort.pdf"),
  paste0(file2,"misc/", "NPS_title.pdf"),
  paste0(file2,"misc/", "NPS_descr.1.pdf"),
  paste0(file2,"misc/", "NPS_descr.2.pdf"),
  paste0(file,"nps pdfs/", "ALL_nps.pdf"),
  paste0(file2,"misc/", "Appendix_title.pdf"),
  paste0(file2,"misc/", "Location_title.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION_", "DIRECTION.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION_", "OPERATIONS.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION_", "PEOPLE.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION_", "ENGAGEMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "VISION.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "STRATEGY.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "LEADERSHIP.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "ADAPTABILITY.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "PERFORMANCE.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "SYSTEMS.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "DEVELOPMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "TALENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "TEAMWORK.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "FIT.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "CUSTOMER.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "CLIMATE.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "SATISFACTION + EFFORT.pdf"),
  paste0(file,"by demo quad and dim plots/", "LOCATION/", "LOCATION- ", "POSITIVITY.pdf"),
  paste0(file,"nps pdfs/", "LOCATION_nps.pdf"),
  paste0(file2,"misc/", "Tenure_title.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE_", "DIRECTION.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE_", "OPERATIONS.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE_", "PEOPLE.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE_", "ENGAGEMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "VISION.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "STRATEGY.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "LEADERSHIP.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "ADAPTABILITY.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "PERFORMANCE.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "SYSTEMS.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "DEVELOPMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "TALENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "TEAMWORK.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "FIT.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "CUSTOMER.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "CLIMATE.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "SATISFACTION + EFFORT.pdf"),
  paste0(file,"by demo quad and dim plots/", "TENURE/", "TENURE- ", "POSITIVITY.pdf"),
  paste0(file,"nps pdfs/", "TENURE_nps.pdf"),
  paste0(file2,"misc/", "Role_title.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE_", "DIRECTION.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE_", "OPERATIONS.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE_", "PEOPLE.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE_", "ENGAGEMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "VISION.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "STRATEGY.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "LEADERSHIP.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "ADAPTABILITY.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "PERFORMANCE.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "SYSTEMS.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "DEVELOPMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "TALENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "TEAMWORK.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "FIT.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "CUSTOMER.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "CLIMATE.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "SATISFACTION + EFFORT.pdf"),
  paste0(file,"by demo quad and dim plots/", "ROLE/", "ROLE- ", "POSITIVITY.pdf"),
  paste0(file,"nps pdfs/", "ROLE_nps.pdf"),
  paste0(file2,"misc/", "Generation_title.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION_", "DIRECTION.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION_", "OPERATIONS.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION_", "PEOPLE.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION_", "ENGAGEMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "VISION.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "STRATEGY.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "LEADERSHIP.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "ADAPTABILITY.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "PERFORMANCE.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "SYSTEMS.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "DEVELOPMENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "TALENT.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "TEAMWORK.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "FIT.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "CUSTOMER.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "CLIMATE.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "SATISFACTION + EFFORT.pdf"),
  paste0(file,"by demo quad and dim plots/", "GENERATION/", "GENERATION- ", "POSITIVITY.pdf"),
  paste0(file,"nps pdfs/", "GENERATION_nps.pdf"),
  paste0(file2,"misc/", "Thank you.pdf")

  
  ), paste0(file, eval(business_unit), "_REPORT_PLOTS.pdf"))

# pdf_combine(c(paste0(file2,"misc/", "Methodology.pdf"),
#               paste0(file2,"misc/", "Images_id_perf.pdf")), "~/Dropbox/testabc.pdf")
